name: Code Review
permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  sun-ai-code-reviewer:
    runs-on: ubuntu-latest
    steps:
      - uses: rogeliojohnoliverio/sun-code-reviewer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ vars.OPENAI_API_KEY }}
